server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/blog
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  config: classpath:log4j2.xml

